<a href="https://colab.research.google.com/github/Andresperez16/data-analyst-project-280/blob/main/dashboard_conversiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ==========================================
# 1. Carga de bibliotecas permitidas
# ==========================================
import pandas as pd
import numpy as np

# Configuración de despliegue
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# ==========================================
# 2. Carga de datasets
# ==========================================
df_visits = pd.read_csv('visits_1k.csv')
df_regs = pd.read_csv('regs_1k.csv')

# Conversión de fechas a formato datetime
df_visits['date'] = pd.to_datetime(df_visits['date'])
df_regs['date'] = pd.to_datetime(df_regs['date'])

# ==========================================
# 3. Tarea 4: Exploración y describe()
# ==========================================
print("==========================================")
print("📊 RESUMEN ESTADÍSTICO - VISITAS (visits_1k.csv)")
print("==========================================")
display(df_visits.describe(include='all'))

print("\n==========================================")
print("📊 RESUMEN ESTADÍSTICO - REGISTROS (regs_1k.csv)")
print("==========================================")
display(df_regs.describe(include='all'))

==========================================
📊 RESUMEN ESTADÍSTICO - VISITAS (visits_1k.csv)
==========================================

                                        uuid platform                                         user_agent                           date
count                                   1000     1000                                               1000                           1000
unique                                   519        3                                                 28                            NaN
top     251a0926-ece3-4d77-aa42-ab569fdf9fe2      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...                            NaN
freq                                       4      954                                                 71                            NaN
mean                                     NaN      NaN                                                NaN  2023-03-02 18:25:04.564000256
min                                      NaN      NaN                                                NaN            2023-03-01 00:05:35
25%                                      NaN      NaN                                                NaN            2023-03-01 12:02:27
50%                                      NaN      NaN                                                NaN     2023-03-01 23:28:04.500000
75%                                      NaN      NaN                                                NaN  2023-03-03 21:42:13.249999872
max                                      NaN      NaN                                                NaN            2023-03-07 23:05:08

==========================================
📊 RESUMEN ESTADÍSTICO - REGISTROS (regs_1k.csv)
==========================================

                              date       user_id                   email platform registration_type
count                         1000  1.000000e+03                    1000     1000              1000
unique                         NaN           NaN                     997        3                 4
top                            NaN           NaN  kimberly90@example.com  android             email
freq                           NaN           NaN                       2      517               446
mean    2023-03-03 10:59:03.900000  4.488623e+06                     NaN      NaN               NaN
min            2023-03-01 00:12:22  2.236800e+04                     NaN      NaN               NaN
25%     2023-03-02 14:08:57.500000  2.235489e+06                     NaN      NaN               NaN
50%            2023-03-03 10:33:06  4.473044e+06                     NaN      NaN               NaN
75%     2023-03-04 07:32:06.500000  6.779707e+06                     NaN      NaN               NaN
max            2023-03-05 22:04:01  8.881772e+06                     NaN      NaN               NaN
std                            NaN  2.620568e+06                     NaN      NaN               NaN

In [3]:
# ==========================================
# CONSULTAS A LA API
# ==========================================
import requests
import pandas as pd

# 1. Definición de URLs y parámetros de rango de fechas
BASE_URL = "https://data-charts-api.hexlet.app"
START_DATE = "2023-03-01"
END_DATE = "2023-09-01"

params = {
    'begin': START_DATE,
    'end': END_DATE
}

# 2. Petición a la API para VISITAS
response_visits = requests.get(f"{BASE_URL}/visits", params=params)

if response_visits.status_code == 200:
    data_visits = response_visits.json()
    df_visits_api = pd.DataFrame(data_visits)
    # Convertir campo datetime a formato de fecha
    df_visits_api['datetime'] = pd.to_datetime(df_visits_api['datetime'])
    print(f"✅ Visitas obtenidas de la API correctamente. Total de registros: {len(df_visits_api)}")
else:
    print(f"❌ Error al consultar /visits: Código {response_visits.status_code}")

# 3. Petición a la API para REGISTROS
response_regs = requests.get(f"{BASE_URL}/registrations", params=params)

if response_regs.status_code == 200:
    data_regs = response_regs.json()
    df_regs_api = pd.DataFrame(data_regs)
    # Convertir campo datetime a formato de fecha
    df_regs_api['datetime'] = pd.to_datetime(df_regs_api['datetime'])
    print(f"✅ Registros obtenidos de la API correctamente. Total de registros: {len(df_regs_api)}")
else:
    print(f"❌ Error al consultar /registrations: Código {response_regs.status_code}")

# 4. Exploración rápida de los DataFrames obtenidos por API
print("\n--- Vista previa Visitas API ---")
display(df_visits_api.head())

print("\n--- Vista previa Registros API ---")
display(df_regs_api.head())

✅ Visitas obtenidas de la API correctamente. Total de registros: 263459
✅ Registros obtenidos de la API correctamente. Total de registros: 21836

--- Vista previa Visitas API ---

                               visit_id platform                                         user_agent            datetime
0  1c9113ed-40ab-47ad-a433-8cc9cd7b99fb      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl... 2023-05-02 01:44:48
1  1c9113ed-40ab-47ad-a433-8cc9cd7b99fb      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl... 2023-04-28 03:29:57
2  2393e373-5b44-426c-a13d-950029210b42      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl... 2023-05-02 01:22:18
3  2393e373-5b44-426c-a13d-950029210b42      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl... 2023-04-30 21:42:57
4  21504d98-8820-4080-8514-a594957e02ce      web  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl... 2023-05-02 19:44:41

--- Vista previa Registros API ---

             datetime                               user_id                       email platform registration_type
0 2023-03-01 07:40:13  2e0f6bb8-b029-4f45-a786-2b53990d37f1           ebyrd@example.org      web            google
1 2023-03-01 13:14:00  f007f97c-9d8b-48b5-af08-119bb8f6d9b6    knightgerald@example.org      web             email
2 2023-03-01 03:05:50  24ff46ae-32b3-4a74-8f27-7cf0b8f32f15  cherylthompson@example.com      web             apple
3 2023-03-01 00:04:47  3e9914e1-5d73-4c23-b25d-b59a3aeb2b60       halldavid@example.org      web             email
4 2023-03-01 18:31:52  27f875fc-f8ce-4aeb-8722-0ecb283d0760        denise86@example.net      web            google